name: Deploy Vue App to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the 'main' branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the previous complete and new runs
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      - name: Setup Node.js # <--- NEW STEP: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your project's required Node.js version (e.g., '18', '16')
          cache: 'npm' # Caches npm dependencies for faster builds

      - name: Install dependencies # <--- NEW STEP: Install project dependencies
        run: npm install

      - name: Build Vue application # <--- NEW STEP: Run the build command
        run: npm run build # This command usually outputs to a 'dist' folder

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # IMPORTANT: Change this path to your build output directory!
          # For Vue CLI/Vite, it's typically 'dist'.
          path: './dist' # <--- CRITICAL CHANGE: Point to the 'dist' folder

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
